#!/bin/bash
initial=initial_search_corridor.txt
for year in 2006 2007 2008 2009 2010; do
    for windage in 0 1 2 3; do
	./ariane_job_getopts -d ${windage}pc_lots$year -n ariane_namelist_sequential_region_$year -i $initial -w $windage
    done
done
